# Generated by Django 3.1 on 2020-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_source',
            field=models.ImageField(height_field='image_height', upload_to='', width_field='image_width'),
        ),
    ]
