# Generated by Django 3.1 on 2020-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200804_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_source',
            field=models.ImageField(height_field='image_height', upload_to='images', width_field='image_width'),
        ),
    ]
