# Generated by Django 3.1 on 2020-08-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200804_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='provider_id',
        ),
    ]
