# Generated by Django 3.1 on 2020-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_remove_image_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='aspect_ratio',
        ),
        migrations.AddField(
            model_name='image',
            name='original_image',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
