# Generated by Django 3.1 on 2020-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200808_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='shape',
            field=models.CharField(default='polygon', max_length=255),
        ),
    ]
