# Generated by Django 3.0.7 on 2020-06-23 15:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_height', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
                ('image_source', models.ImageField(height_field='image_height', upload_to='images', width_field='image_width')),
                ('provider_id', models.CharField(max_length=20, null=True)),
                ('aspect_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('annotation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('label', models.CharField(max_length=300)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Image')),
            ],
        ),
    ]
